In [1]:
import pandas as pd

df = pd.read_excel('combo_results.xlsx')

method_averages = {}

method_averages['데이터_선택'] = df.groupby('데이터_선택')['F1_점수'].mean().sort_values(ascending=False)
method_averages['피처_방법'] = df.groupby('피처_방법')['F1_점수'].mean().sort_values(ascending=False)
method_averages['모델_방법'] = df.groupby('모델_방법')['F1_점수'].mean().sort_values(ascending=False)
method_averages['리샘플링'] = df.groupby('리샘플링')['F1_점수'].mean().sort_values(ascending=False)
method_averages['손실함수'] = df.groupby('손실함수')['F1_점수'].mean().sort_values(ascending=False)

for method_type, averages in method_averages.items():
    print(f"\n=== {method_type} 별 평균 F1 점수 ===")
    for method, score in averages.items():
        print(f"{method:20} : {score:.3f}")

# 전체 방법별 평균을 하나의 DataFrame으로 생성
summary_data = []
for method_type, averages in method_averages.items():
    for method, score in averages.items():
        summary_data.append({
            '방법_유형': method_type,
            '방법': method,
            '평균_F1점수': round(score, 3)
        })

summary_df = pd.DataFrame(summary_data)

# 피벗 테이블로 변환
pivot_table = summary_df.pivot(index='방법', columns='방법_유형', values='평균_F1점수')
print(f"\n=== 전체 방법별 평균 요약 ===")
pivot_table.fillna('-')

c:\Users\user\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

=== 데이터_선택 별 평균 F1 점수 ===
first_last           : 0.402
max_disease_change   : 0.401

=== 피처_방법 별 평균 F1 점수 ===
feature_engineering  : 0.408
base                 : 0.396

=== 모델_방법 별 평균 F1 점수 ===
ensemble             : 0.462
base                 : 0.376
regularized          : 0.368

=== 리샘플링 별 평균 F1 점수 ===
smote                : 0.446
none                 : 0.358

=== 손실함수 별 평균 F1 점수 ===
WeightedCE_log       : 0.404
CrossEntropy         : 0.402
FocalLoss            : 0.399

=== 전체 방법별 평균 요약 ===

방법_유형               데이터_선택   리샘플링  모델_방법   손실함수  피처_방법
방법
CrossEntropy             -      -      -  0.402      -
FocalLoss                -      -      -  0.399      -
WeightedCE_log           -      -      -  0.404      -
base                     -      -  0.376      -  0.396
ensemble                 -      -  0.462      -      -
feature_engineering      -      -      -      -  0.408
first_last           0.402      -      -      -      -
max_disease_change   0.401      -      -      -      -
none                     -  0.358      -      -      -
regularized              -      -  0.368      -      -
smote                    -  0.446      -      -      -

In [2]:
summary_df

     방법_유형                   방법  평균_F1점수
0   데이터_선택           first_last    0.402
1   데이터_선택   max_disease_change    0.401
2    피처_방법  feature_engineering    0.408
3    피처_방법                 base    0.396
4    모델_방법             ensemble    0.462
5    모델_방법                 base    0.376
6    모델_방법          regularized    0.368
7     리샘플링                smote    0.446
8     리샘플링                 none    0.358
9     손실함수       WeightedCE_log    0.404
10    손실함수         CrossEntropy    0.402
11    손실함수            FocalLoss    0.399